# Generated by Django 4.2 on 2023-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
